"""create users, books

Revision ID: 402b2dfeb53e
Revises: 
Create Date: 2020-11-05 12:27:03.453099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '402b2dfeb53e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
        sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
        sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table(
        'books',
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
        sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
        sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table(
        'mails',
        sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
        sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
        sa.Column('mail_id', sa.String(length=1024), nullable=False),
        sa.Column('user_id', sa.String(length=1024), nullable=False),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('your_name', sa.String(length=1024), nullable=True),
        sa.Column('your_mail_address', sa.String(length=1024), nullable=True),
        sa.Column('ai_answer', sa.Text(), nullable=True),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('rank', sa.String(length=1024), nullable=True),
        sa.Column('send_time', sa.String(length=1024), nullable=True),
        sa.Column('send_flag', sa.Boolean(), nullable=True),

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('mails')
    # ### end Alembic commands ###
