"""Add created_at to mails

Revision ID: b6028fa93ebc
Revises: 402b2dfeb53e
Create Date: 2024-09-20 15:30:00.601361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6028fa93ebc'
down_revision = '402b2dfeb53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('title', sa.String(length=1024), server_default='質問のタイトル', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'title')
    # ### end Alembic commands ###
